### PR TITLE
add license boilerplate and workflow to check it

### PR DESCRIPTION
**Pull request by cpanato**
- make all boilerplate header similar to each other
- add ci verify to validate the boilerplates

more context slack 🧵 : https://sigstore.slack.com/archives/C01CQ3L3H8X/p1617957935102100

/assign @dlorenc @lukehinds

### CODE REVIEW

**Review by mbestavros — CHANGES_REQUESTED** [review]
Good idea, and thanks for the PR! I tend to be more in favor of SPDX headers than full license boilerplate, though -- less cluttered and easier to maintain. Not sure if that's possible with `addlicense` or not, but I did at one point write a Github action to test for SPDX license headers --  I'll see if I can dig that up.

**Comment by cpanato** [comment]
@mbestavros can you give to me an example of how you would like to have the headers? then I can see how to implement it

**Comment by mbestavros** [comment]
@cpanato [Here's](https://github.com/actions-automation/pull-request-responsibility/blob/main/src/assign#L2) a good example of an SPDX Apache 2 license header, and [here's](https://spdx.github.io/spdx-spec/appendix-V-using-SPDX-short-identifiers-in-source-files/) some additional documentation.

**Comment by cpanato** [comment]
@mbestavros thanks, i will make the changes during the week

**Comment by cpanato** [comment]
@mbestavros the addlicense does not work quite well with this type of format, it tries to add it all the time.

I will remove the GH action to check the boilerplate and keep the headers, this is not a huge project that will have several files to validate :)

**Review by mbestavros — CHANGES_REQUESTED** [review]
`COPYRIGHT.txt` is not needed: we already have the top-level [`LICENSE`](https://github.com/sigstore/sigstore-git-verifier/blob/main/LICENSE) file, which includes a full copy of the Apache 2.0 license.

Otherwise, the headers look good!

**Review by mbestavros — APPROVED** [review]
LGTM!

**Pull request merged**
